DELETE FROM `playercreateinfo_spell_custom`;
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 0, 33388, 'All - Apprentice Riding');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 0, 34091, 'All - Artisan Riding');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 0, 54197, 'All - Cold Weather Flying');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 0, 34090, 'All - Expert Riding');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 0, 90267, 'All - Flight Master\'s License');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 0, 33391, 'All - Journeyman Riding');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 0, 90265, 'All - Master Riding');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 48707, 'Death Knight - Anti-Magic Shell');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 42650, 'Death Knight - Army of the Dead');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 48721, 'Death Knight - Blood Boil');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 48263, 'Death Knight - Blood Presence');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 45529, 'Death Knight - Blood Tap');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 45524, 'Death Knight - Chains of Ice');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 56222, 'Death Knight - Dark Command');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 77606, 'Death Knight - Dark Simulacrum');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 43265, 'Death Knight - Death and Decay');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 48743, 'Death Knight - Death Pact');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 49998, 'Death Knight - Death Strike');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 47568, 'Death Knight - Empower Rune Weapon');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 85948, 'Death Knight - Festering Strike');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 57330, 'Death Knight - Horn of Winter');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 48792, 'Death Knight - Icebound Fortitude');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 86471, 'Death Knight - Mastery (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 47528, 'Death Knight - Mind Freeze');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 73975, 'Death Knight - Necrotic Strike');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 49020, 'Death Knight - Obliterate');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 77575, 'Death Knight - Outbreak');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 82246, 'Death Knight - Parry (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 3714, 'Death Knight - Path of Frost');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 50842, 'Death Knight - Pestilience');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 86524, 'Death Knight - Plate Specialization (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 61999, 'Death Knight - Raise Ally');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 46584, 'Death Knight - Raise Dead');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 56815, 'Death Knight - Rune Strike');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 81229, 'Death Knight - Runic Empowerment (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 47476, 'Death Knight - Strangulate');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 32, 48265, 'Death Knight - Unholy Presence');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 1066, 'Druid - Aquatic Form');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 22812, 'Druid - Barkskin');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 5211, 'Druid - Bash');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 5487, 'Druid - Bear Form');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 768, 'Druid - Cat Form');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 5209, 'Druid - Challenging Roar');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 1082, 'Druid - Claw');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 8998, 'Druid - Cower');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 33786, 'Druid - Cyclone');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 1850, 'Druid - Dash');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 99, 'Druid - Demoralizing Roar');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 5229, 'Druid - Enrage');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 339, 'Druid - Entangling Roots');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 770, 'Druid - Faerie Fire');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 16857, 'Druid - Faerie Fire (Feral)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 20719, 'Druid - Feline Grace');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 22568, 'Druid - Ferocious Bite');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 33943, 'Druid - Flight Form');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 22842, 'Druid - Frenzied Regeneration');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 6795, 'Druid - Growl');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 5185, 'Druid - Healing Touch');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 2637, 'Druid - Hibernate');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 16914, 'Druid - Hurricane');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 29166, 'Druid - Innervate');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 5570, 'Druid - Insect Swarm');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 33745, 'Druid - Lacerate');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 86530, 'Druid - Leather Specialization (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 33763, 'Druid - Lifebloom');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 22570, 'Druid - Maim');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 1126, 'Druid - Mark of the Wild');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 86470, 'Druid - Mastery (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 6807, 'Druid - Maul');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 8921, 'Druid - Moonfire');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 16689, 'Druid - Nature\'s Grasp');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 50464, 'Druid - Nourish');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 16864, 'Druid - Omen of Clarity (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 9005, 'Druid - Pounce');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 5215, 'Druid - Prowl');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 1822, 'Druid - Rake');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 6785, 'Druid - Ravage');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 20484, 'Druid - Rebirth');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 8936, 'Druid - Regrowth');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 774, 'Druid - Rejuvenation');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 2782, 'Druid - Remove Corruption');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 50769, 'Druid - Revive');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 1079, 'Druid - Rip');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 62600, 'Druid - Savage Defense (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 52610, 'Druid - Savage Roar');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 5221, 'Druid - Shred');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 80964, 'Druid - Skull Bash (Bear Form)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 80965, 'Druid - Skull Bash (Cat Form)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 2908, 'Druid - Soothe');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 77761, 'Druid - Stampeding Roar (Bear Form)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 77764, 'Druid - Stampeding Roar (Cat Form)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 2912, 'Druid - Starfire');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 40120, 'Druid - Swift Flight Form');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 779, 'Druid - Swipe (Bear Form)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 62078, 'Druid - Swipe (Cat Form)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 18960, 'Druid - Teleport: Moonglade');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 467, 'Druid - Thorns');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 77758, 'Druid - Thrash');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 5217, 'Druid - Tiger\'s Fury');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 740, 'Druid - Tranquility');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 783, 'Druid - Travel Form');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 88747, 'Druid - Wild Mushroom');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1024, 88751, 'Druid - Wild Mushroom: Detonate');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 5118, 'Hunter - Aspect of the Cheetah');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 82661, 'Hunter - Aspect of the Fox');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 13165, 'Hunter - Aspect of the Hawk');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 13159, 'Hunter - Aspect of the Pack');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 20043, 'Hunter - Aspect of the Wild');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 1462, 'Hunter - Beast Lore');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 83242, 'Hunter - Call Pet 2');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 83243, 'Hunter - Call Pet 3');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 83244, 'Hunter - Call Pet 4');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 83245, 'Hunter - Call Pet 5');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 51753, 'Hunter - Camouflage');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 77767, 'Hunter - Cobra Shot');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 5116, 'Hunter - Concussive Shot');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 93321, 'Hunter - Control Pet (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 19263, 'Hunter - Deterrence');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 781, 'Hunter - Disengage');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 2641, 'Hunter - Dismiss Pet');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 20736, 'Hunter - Distracting Shot');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 674, 'Hunter - Dual Wield (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 6197, 'Hunter - Eagle Eye');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 13813, 'Hunter - Explosive Trap');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 6991, 'Hunter - Feed Pet');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 5384, 'Hunter - Feign Death');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 1543, 'Hunter - Flare');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 1499, 'Hunter - Freezing Trap');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 1130, 'Hunter - Hunter\'s Mark');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 13809, 'Hunter - Ice Trap');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 13795, 'Hunter - Immolation Trap');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 34026, 'Hunter - Kill Command');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 53351, 'Hunter - Kill Shot');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 86528, 'Hunter - Mail Specialization (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 53271, 'Hunter - Master\'s Call');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 86472, 'Hunter - Mastery (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 136, 'Hunter - Mend Pet');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 34477, 'Hunter - Misdirection');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 2643, 'Hunter - Multi-Shot');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 82243, 'Hunter - Parry (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 3045, 'Hunter - Rapid Fire');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 2973, 'Hunter - Raptor Strike');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 1513, 'Hunter - Scare Beast');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 19503, 'Hunter - Scatter Shot');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 1978, 'Hunter - Serpent Sting');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 34600, 'Hunter - Snake Trap');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 56641, 'Hunter - Steady Shot');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 1515, 'Hunter - Tame Beast');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 19801, 'Hunter - Tranquilizing Shot');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 77769, 'Hunter - Trap Launcher');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 82654, 'Hunter - Widow Venom');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 4, 2974, 'Hunter - Wing Clip');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 30451, 'Mage - Arcane Blast');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 1459, 'Mage - Arcane Brilliance');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 1449, 'Mage - Arcane Explosion');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 5143, 'Mage - Arcane Missles');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 1953, 'Mage - Blink');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 10, 'Mage - Blizzard');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 120, 'Mage - Cone of Cold');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 759, 'Mage - Conjure Mana Gem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 42955, 'Mage - Conjure Refreshment');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 2139, 'Mage - Counterspell');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 12051, 'Mage - Evocation');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 2136, 'Mage - Fire Blast');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 82731, 'Mage - Flame Orb');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 2120, 'Mage - Flamestrike');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 7302, 'Mage - Frost Armor');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 122, 'Mage - Frost Nova');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 116, 'Mage - Frostbolt');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 44614, 'Mage - Frostfire Bolt');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 45438, 'Mage - Ice Block');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 30455, 'Mage - Ice Lance');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 66, 'Mage - Invisibility');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 6117, 'Mage - Mage Armor');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 543, 'Mage - Mage Ward');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 1463, 'Mage - Mana Shield');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 86473, 'Mage - Mastery (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 55342, 'Mage - Mirror Image');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 30482, 'Mage - Molten Armor');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 118, 'Mage - Polymorph');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 475, 'Mage - Remove Curse');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 82676, 'Mage - Ring of Frost');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 43987, 'Mage - Ritual of Refreshment');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 2948, 'Mage - Scorch');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 130, 'Mage - Slow Fall');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 30449, 'Mage - Spellsteal');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 80353, 'Mage - Time Warp');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 128, 89744, 'Mage - Wizardry (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 31884, 'Paladin - Avenging Wrath');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 20217, 'Paladin - Blessing of Kings');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 19740, 'Paladin - Blessing of Might');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 4987, 'Paladin - Cleanse');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 19746, 'Paladin - Concentration Aura');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 26573, 'Paladin - Consecration');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 32223, 'Paladin - Crusader Aura');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 465, 'Paladin - Devotion Aura');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 82326, 'Paladin - Divine Light');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 54428, 'Paladin - Divine Plea');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 498, 'Paladin - Divine Protection');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 642, 'Paladin - Divine Shield');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 879, 'Paladin - Exorcism');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 19750, 'Paladin - Flash of Light');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 86150, 'Paladin - Guardian of Ancient Kings');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 853, 'Paladin - Hammer of Justice');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 24275, 'Paladin - Hammer of Wrath');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 1044, 'Paladin - Hand of Freedom');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 1022, 'Paladin - Hand of Protection');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 62124, 'Paladin - Hand of Reckoning');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 6940, 'Paladin - Hand of Sacrifice');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 1038, 'Paladin - Hand of Salvation');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 635, 'Paladin - Holy Light');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 82327, 'Paladin - Holy Radiance');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 2812, 'Paladin - Holy Wrath');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 84963, 'Paladin - Inquisition');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 20271, 'Paladin - Judgement');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 633, 'Paladin - Lay on Hands');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 86474, 'Paladin - Mastery (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 82242, 'Paladin - Parry (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 86525, 'Paladin - Plate Specialization (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 96231, 'Paladin - Rebuke');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 7328, 'Paladin - Redemption');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 19891, 'Paladin - Resistance Aura');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 7294, 'Paladin - Retribution Aura');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 31789, 'Paladin - Righteous Defense');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 25780, 'Paladin - Righteous Fury');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 20165, 'Paladin - Seal of Insight');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 20164, 'Paladin - Seal of Justice');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 20154, 'Paladin - Seal of Righteousness');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 31801, 'Paladin - Seal of Truth');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 10326, 'Paladin - Turn Evil');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 2, 85673, 'Paladin - Word of Glory');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 32546, 'Priest - Binding Heal');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 528, 'Priest - Cure Disease');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 2944, 'Priest - Devouring Plague');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 527, 'Priest - Dispel Magic');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 64843, 'Priest - Divine Hymn');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 586, 'Priest - Fade');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 6346, 'Priest - Fear Ward');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 2061, 'Priest - Flash Heal');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 2060, 'Priest - Greater Heal');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 2050, 'Priest - Heal');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 14914, 'Priest - Holy Fire');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 15237, 'Priest - Holy Nova');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 64901, 'Priest - Hymn of Hope');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 588, 'Priest - Inner Fire');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 73413, 'Priest - Inner Will');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 73325, 'Priest - Leap of Faith');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 1706, 'Priest - Levitate');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 8129, 'Priest - Mana Burn');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 32375, 'Priest - Mass Dispel');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 86475, 'Priest - Mastery (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 8092, 'Priest - Mind Blast');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 605, 'Priest - Mind Control');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 48045, 'Priest - Mind Sear');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 453, 'Priest - Mind Soothe');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 73510, 'Priest - Mind Spike');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 2096, 'Priest - Mind Vision');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 89745, 'Priest - Mysticism (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 21562, 'Priest - Power Word: Fortitude');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 17, 'Priest - Power Word: Shield');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 596, 'Priest - Prayer of Healing');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 33076, 'Priest - Prayer of Mending');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 8122, 'Priest - Psychic Scream');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 139, 'Priest - Renew');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 2006, 'Priest - Resurrection');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 9484, 'Priest - Shackle Undead');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 27683, 'Priest - Shadow Protection');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 32379, 'Priest - Shadow Word: Death');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 589, 'Priest - Shadow Word: Pain');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 16, 34433, 'Priest - Shadowfiend');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 8676, 'Rogue - Ambush');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 53, 'Rogue - Backstab');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 2094, 'Rogue - Blind');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 1833, 'Rogue - Cheap Shot');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 31224, 'Rogue - Cloak of Shadows');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 74001, 'Rogue - Combat Readiness');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 26679, 'Rogue - Deadly Throw');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 2836, 'Rogue - Detect Traps (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 1842, 'Rogue - Disarm Trap');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 51722, 'Rogue - Dismantle');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 1725, 'Rogue - Distract');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 32645, 'Rogue - Envenom');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 5277, 'Rogue - Evasion');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 2098, 'Rogue - Eviscerate');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 8647, 'Rogue - Expose Armor');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 51723, 'Rogue - Fan of Knives');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 1966, 'Rogue - Feint');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 703, 'Rogue - Garrote');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 1776, 'Rogue - Gouge');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 1766, 'Rogue - Kick');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 408, 'Rogue - Kidney Shot');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 86531, 'Rogue - Leather Specialization (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 86476, 'Rogue - Mastery (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 82245, 'Rogue - Parry (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 1804, 'Rogue - Pick Lock');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 921, 'Rogue - Pick Pocket');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 73651, 'Rogue - Recuperate');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 73981, 'Rogue - Redirect');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 1943, 'Rogue - Rupture');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 1860, 'Rogue - Safe Fall (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 6770, 'Rogue - Sap');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 5938, 'Rogue - Shiv');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 5171, 'Rogue - Slice and Dice');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 76577, 'Rogue - Smoke Bomb');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 2983, 'Rogue - Sprint');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 1784, 'Rogue - Stealth');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 57934, 'Rogue - Tricks of the Trade');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 8, 1856, 'Rogue - Vanish');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 2008, 'Shaman - Ancestral Spirit');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 556, 'Shaman - Astral Recall');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 76780, 'Shaman - Bind Elemental');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 66843, 'Shaman - Call of the Ancestors');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 66842, 'Shaman - Call of the Elements');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 66844, 'Shaman - Call of the Spirits');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 1064, 'Shaman - Chain Heal');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 421, 'Shaman - Chain Lightning');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 51886, 'Shaman - Cleanse Spirit');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8042, 'Shaman - Earth Shock');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 2062, 'Shaman - Earth Elemental Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 2484, 'Shaman - Earthbind Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 51730, 'Shaman - Earthliving Weapon');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8184, 'Shaman - Elemental Resistance Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 6196, 'Shaman - Far Sight');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 2894, 'Shaman - Fire Elemental Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 1535, 'Shaman - Fire Nova');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8050, 'Shaman - Flame Shock');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8024, 'Shaman - Flametongue Weapon');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8227, 'Shaman - Flametongue Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8056, 'Shaman - Frost Shock');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8033, 'Shaman - Frostbrand Weapon');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 2645, 'Shaman - Ghost Wolf');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 77472, 'Shaman - Greater Healing Wave');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8177, 'Shaman - Grounding Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 73920, 'Shaman - Healing Rain');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 5394, 'Shaman - Healing Stream Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8004, 'Shaman - Healing Surge');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 331, 'Shaman - Healing Wave');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 32182, 'Shaman - Heroism');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 51514, 'Shaman - Hex');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 51505, 'Shaman - Lava Burst');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 324, 'Shaman - Lightning Shield');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8190, 'Shaman - Magma Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 86529, 'Shaman - Mail Specialization (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 5675, 'Shaman - Mana Spring Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 86477, 'Shaman - Mastery (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 73899, 'Shaman - Primal Strike');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 370, 'Shaman - Purge');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 20608, 'Shaman - Reincarnation (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8017, 'Shaman - Rockbiter Weapon');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 3599, 'Shaman - Searing Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 79206, 'Shaman - Spiritwalker\'s Grace');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 5730, 'Shaman - Stoneclaw Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8071, 'Shaman - Stoneskin Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8075, 'Shaman - Strength of Earth Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 87718, 'Shaman - Totem of Tranquil Mind');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 36936, 'Shaman - Totemic Recall');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8143, 'Shaman - Tremor Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 73680, 'Shaman - Unleash Elements');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 131, 'Shaman - Water Breathing');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 52127, 'Shaman - Water Shield');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 546, 'Shaman - Water Walking');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 57994, 'Shaman - Wind Shear');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8512, 'Shaman - Windfury Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 8232, 'Shaman - Windfury Weapon');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 64, 3738, 'Shaman - Wrath of Air Totem');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 980, 'Warlock - Bane of Agony');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 603, 'Warlock - Bane of Doom');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 710, 'Warlock - Banish');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 93375, 'Warlock - Control Demon');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 172, 'Warlock - Corruption');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 6201, 'Warlock - Create Healthstone');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 693, 'Warlock - Create Soulstone');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 1490, 'Warlock - Curse of the Elements');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 1714, 'Warlock - Curse of Tongues');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 702, 'Warlock - Curse of Weakness');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 80398, 'Warlock - Dark Intent');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 6789, 'Warlock - Death Coil');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 687, 'Warlock - Demon Armor');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 77801, 'Warlock - Demon Soul');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 48018, 'Warlock - Demonic Circle: Summon');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 48020, 'Warlock - Demonic Circle: Teleport');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 689, 'Warlock - Drain Life');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 1120, 'Warlock - Drain Soul');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 1098, 'Warlock - Enslave Demon');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 126, 'Warlock - Eye of Kilrogg');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 5782, 'Warlock - Fear');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 28176, 'Warlock - Fel Armor');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 77799, 'Warlock - Fel Flame');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 755, 'Warlock - Health Funnel');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 1949, 'Warlock - Hellfire');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 5484, 'Warlock - Howl of Terror');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 348, 'Warlock - Immolate');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 29722, 'Warlock - Incinerate');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 1454, 'Warlock - Life Tap');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 86478, 'Warlock - Mastery (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 86091, 'Warlock - Nethermancy (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 5740, 'Warlock - Rain of Fire');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 29893, 'Warlock - Ritual of Souls');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 698, 'Warlock - Ritual of Summoning');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 5676, 'Warlock - Searing Pain');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 27243, 'Warlock - Seed of Corruption');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 6229, 'Warlock - Shadow Ward');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 47897, 'Warlock - Shadowflame');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 6353, 'Warlock - Soul Fire');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 79268, 'Warlock - Soul Harvest');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 19028, 'Warlock - Soul Link');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 74434, 'Warlock - Soulburn');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 29858, 'Warlock - Soulshatter');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 18540, 'Warlock - Summon Doomguard');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 691, 'Warlock - Summon Felhunter');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 1122, 'Warlock - Summon Infernal');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 712, 'Warlock - Summon Succubus');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 697, 'Warlock - Summon Voidwalker');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 256, 5697, 'Warlock - Unending Breath');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 6673, 'Warrior - Battle Shout');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 18499, 'Warrior - Berserker Rage');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 2458, 'Warrior - Berserker Stance');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 1161, 'Warrior - Challenging Shout');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 100, 'Warrior - Charge');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 845, 'Warrior - Cleave');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 86346, 'Warrior - Colossus Smash');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 469, 'Warrior - Commanding Shout');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 71, 'Warrior - Defensive Stance');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 1160, 'Warrior - Demoralizing Shout');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 676, 'Warrior - Disarm');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 55694, 'Warrior - Enraged Regeneration');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 5308, 'Warrior - Execute');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 1715, 'Warrior - Hamstring');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 6544, 'Warrior - Heroic Leap');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 78, 'Warrior - Heroic Strike');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 57755, 'Warrior - Heroic Throw');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 1134, 'Warrior - Inner Rage');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 20252, 'Warrior - Intercept');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 3411, 'Warrior - Intervene');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 5246, 'Warrior - Intimidating Shout');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 86479, 'Warrior - Mastery (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 7384, 'Warrior - Overpower');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 3127, 'Warrior - Parry (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 86526, 'Warrior - Plate Specialization (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 6552, 'Warrior - Pummel');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 97462, 'Warrior - Rallying Cry');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 1719, 'Warrior - Recklessness');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 772, 'Warrior - Rend');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 20230, 'Warrior - Retaliation');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 6572, 'Warrior - Revenge');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 64382, 'Warrior - Shattering Throw');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 2565, 'Warrior - Shield Block');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 871, 'Warrior - Shield Wall');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 1464, 'Warrior - Slam');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 23920, 'Warrior - Spell Reflection');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 12678, 'Warrior - Stance Mastery (Passive)');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 7386, 'Warrior - Sunder Armor');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 355, 'Warrior - Taunt');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 6343, 'Warrior - Thunder Clap');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 34428, 'Warrior - Victory Rush');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES (0, 1, 1680, 'Warrior - Whirlwind');
