DROP TABLE IF EXISTS `creatureimmunities_dbc`;
CREATE TABLE `creatureimmunities_dbc` (  
  `ID` INT(8) UNSIGNED NOT NULL,
  `School` INT(8) UNSIGNED DEFAULT 0,
  `DispelType` INT(8) UNSIGNED DEFAULT 0,
  `MechanicsAllowed` INT(8) UNSIGNED DEFAULT 0,
  `Mechanic` INT(8) UNSIGNED DEFAULT 0,
  `EffectsAllowed` INT(8) UNSIGNED DEFAULT 0,
  `Effect0` INT(8) UNSIGNED DEFAULT 0,
  `Effect1` INT(8) UNSIGNED DEFAULT 0,
  `Effect2` INT(8) UNSIGNED DEFAULT 0,
  `Effect3` INT(8) UNSIGNED DEFAULT 0,
  `Effect4` INT(8) UNSIGNED DEFAULT 0,
  `Effect5` INT(8) UNSIGNED DEFAULT 0,
  `StatesAllowed` INT(8) UNSIGNED DEFAULT 0,
  `State0` INT(8) UNSIGNED DEFAULT 0,
  `State1` INT(8) UNSIGNED DEFAULT 0,
  `State2` INT(8) UNSIGNED DEFAULT 0,
  `State3` INT(8) UNSIGNED DEFAULT 0,
  `State4` INT(8) UNSIGNED DEFAULT 0,
  `State5` INT(8) UNSIGNED DEFAULT 0,
  `State6` INT(8) UNSIGNED DEFAULT 0,
  `State7` INT(8) UNSIGNED DEFAULT 0,
  `State8` INT(8) UNSIGNED DEFAULT 0,
  `State9` INT(8) UNSIGNED DEFAULT 0,
  `State10` INT(8) UNSIGNED DEFAULT 0,
  `State11` INT(8) UNSIGNED DEFAULT 0,
  `Flags` INT(8) UNSIGNED DEFAULT 0,
  PRIMARY KEY (`ID`)
);

ALTER TABLE `spelleffect_dbc`   
	ADD COLUMN `EffectAttributes` INT(10) UNSIGNED DEFAULT 0 NOT NULL AFTER `EffectIndex`;
